# Generated by Django 5.2.1 on 2025-06-16 13:28

import django.utils.timezone
import menus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ticket_quantity", models.PositiveIntegerField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("656910038", "656910038"),
                            ("678789520", "678789520"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.RemoveField(
            model_name="dailymenu",
            name="image_path",
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=menus.models.menu_image_path
            ),
        ),
    ]
